### ISSUE TITLE
Unable to install on Nexus6, Android 5.1, rooted

### ISSUE THREAD

**Issue by markzhai** [kyze8439690/DevelopQuickSetting#5]
Unable to install on Nexus6, Android 5.1, rooted.

After "install and reboot" twice, I still saw "INSTALL AND REBOOT"

**Comment by markzhai** [comment]
found same issue on nexus 5, Android 5.0.1(same stock rom), rooted

**Comment by kyze8439690** [comment]
After click "install and reboot", the applicatin will do thing below:
1.copy the apk file to /system/priv-app/DevelopQuickSetting/DevelopQuickSetting.apk(android 5.0 +)
2.reboot device

To achive this, application run shell below:

```
su
mount -o rw,remount /system
mkdir -p /system/priv-app/DevelopQuickSetting
cat [source apk file path] > /system/priv-app/DevelopQuickSetting/DevelopQuickSetting.apk
chmod 644 /system/priv-app/DevelopQuickSetting/DevelopQuickSetting.apk
pkill zygote #or reboot manualy.
```

I am sorry that I didn't have the devices run system you have. So can you try the run shell above in terminal and tell me whether they work? Maybe one of these commands run failed. Thank you :)

**Comment by kyze8439690** [comment]
Now this application can be used without install.
